// <auto-generated />
using GitHyperBot.Resources.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace GitHyperBot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20180512035002_add-migration Tabelas")]
    partial class addmigrationTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("GitHyperBot.Resources.Database.Accounts", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Mute")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<uint>("NumberOfWarning");

                    b.Property<uint>("Points");

                    b.Property<uint>("Xp");

                    b.HasKey("UserId");

                    b.ToTable("TableAccounts");
                });

            modelBuilder.Entity("GitHyperBot.Resources.Database.Guilds", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("BoasVindasBool");

                    b.Property<string>("BoasVindasDescription");

                    b.Property<bool>("BoasVindasPvBool");

                    b.Property<string>("BoasVindasPvDescription");

                    b.Property<string>("BoasVindasPvField1Descri");

                    b.Property<string>("BoasVindasPvField1Title");

                    b.Property<string>("BoasVindasPvField2Descri");

                    b.Property<string>("BoasVindasPvField2Title");

                    b.Property<string>("BoasVindasPvField3Descri");

                    b.Property<string>("BoasVindasPvField3Title");

                    b.Property<string>("BoasVindasPvFooter");

                    b.Property<string>("BoasVindasPvTitle");

                    b.Property<string>("BoasVindasPvUrl");

                    b.Property<string>("BoasVindasTitle");

                    b.Property<string>("BoasVindasUrl");

                    b.Property<ulong>("IdChatConvites");

                    b.Property<ulong>("IdChatGeral");

                    b.Property<ulong>("IdChatLog");

                    b.Property<ulong>("IdMsgRegistro");

                    b.Property<ulong>("IdMsgRegras");

                    b.HasKey("GuildId");

                    b.ToTable("TableGuilds");
                });
#pragma warning restore 612, 618
        }
    }
}
